### ISSUE TITLE
Fedora - `sh: file: command not found`

### ISSUE THREAD

**Issue by schloerke** [r-hub/rhub-server#26]
* Live example: 
  * https://builder.r-hub.io/status/reactlog_1.0.0.tar.gz-2a15acc55edd41e6bef5025f112f0470#L1152
* Build ID: 
  * reactlog_1.0.0.tar.gz-2a15acc55edd41e6bef5025f112f0470
* Platform: 
  * Fedora Linux, R-devel, clang, gfortran

**Comment by gaborcsardi** [comment]
Duplicate of this: https://github.com/r-hub/rhub/issues/216
